### ISSUE TITLE
Bug or breaking change? Model class must now implement `.primary_key`

### ISSUE THREAD

**Issue by bensheldon** [rails/globalid#166]
I noticed a recent change now requires any class that has `include GlobalID::Identification` must now also respond to `.primary_key`. I think it came from https://github.com/rails/globalid/pull/163

I'm not sure if GlobalId is intended to be used on _only_ Active Record / Active Model, but that's what I've been doing. The readme says:

> Mix GlobalID::Identification into any model with a `#find(id)` class method

If model in this sense means generically "a domain model" than I think this is a bug or breaking change. And if not, the readme needs to be updated to say both `.find` _and_ `.primary_key`.

**Comment by ghiculescu** [comment]
Just saw this, made this PR: https://github.com/rails/globalid/pull/168

**Comment by kyrofa** [comment]
Just hit this myself. In my book, this is either a bug requiring this fix, or a breaking change requiring a major version bump.

**Comment by kyrofa** [comment]
Thanks for the quick fix, folks.

> Hi folks, initially this was an intentional breaking change [...]

@nvasilevski just to confirm, are you saying you forgot to bump the major version, or are you saying breaking changes in a minor version bump is to be expected from globalid? I don't mean to pass judgement, I just need to understand the versioning scheme of one of my dependencies. Basically: can I continue using a pessimistic operator, or should I be pinning globalid?

**Comment by nvasilevski** [comment]
>are you saying you forgot to bump the major version

So since release management is a core team's responsibility I couldn't tell whether a breaking change was supposed to be released under a major version. But I wanted to clarify that it was a deliberate decision to require `primary_key` and we knew about non-AR models being broken since basically all models in tests had to implement `primary_key`. It wasn't the most optimal decision at the end of the day and I'm glad we end up with a solution to keep backwards compatibility

**Comment by kyrofa** [comment]
@rafaelfranca would you mind speaking to the versioning strategy, here?

**Comment by rafaelfranca** [comment]
There isn't any breaking change. `primary_key` method isn't mandatory in the objects.

**Comment by rafaelfranca** [comment]
But if there was a intentional breaking change I'd be bumping the major version, not the minor.

**Comment by kyrofa** [comment]
> But if there was a intentional breaking change I'd be bumping the major version, not the minor.

I _think_ this means that not bumping the major version was a mistake. Which is just fine, mistakes happen. But then:

> There isn't any breaking change. primary_key method isn't mandatory in the objects.

This makes me doubt. Do you not look at what happened as a breaking change?

Haha, I'm a smidge confused now. @rafaelfranca, to clarify, v1.2.0 made `primary_key` mandatory, when it wasn't mandatory on v1.1.0. According to @nvasilevski above, that _was_ an intentional breaking change. You're correct, that was fixed in #168 (released in v1.2.1), but this DID break.
